version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install mkdocs
      - pip install mkdocs-material
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt